name: Java CI Build & Deploy

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # OpenJDK vendor
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./ezapi_poc/infra_poc

      - name: List target files
        run: ls -l ./ezapi_poc/infra_poc/target

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-artifact
          path: ./ezapi_poc/infra_poc/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/dev'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: java-artifact

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts (optional)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy artifact to Azure VM
        run: |
          scp *.jar azureuser@20.197.6.140:/home/azureuser/deployments/
          ssh azureuser@20.197.6.140 "bash /home/azureuser/deployments/deploy_script.sh"

